version: "3.4"
services: 
  app:
    image: traefikapp    
    ports:
      - "3000:3000"
    deploy: 
      replicas: 2
  gateway:
    image: traefik:1.4
    ports:
      - "3000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
